# Generated by Django 5.2.12 on 2026-03-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('interval_value', models.PositiveIntegerField(verbose_name='Intervallwert')),
                ('interval_unit', models.CharField(choices=[('days', 'Tage'), ('weeks', 'Wochen'), ('months', 'Monate'), ('years', 'Jahre')], max_length=10, verbose_name='Intervall-Einheit')),
                ('warning_days', models.PositiveIntegerField(default=0, verbose_name='Warnungstage')),
                ('responsible_person', models.CharField(blank=True, max_length=255, verbose_name='Verantwortlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='assets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Wartungsplan',
                'verbose_name_plural': 'Wartungsplaene',
                'ordering': ['asset__asset_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('performed_on', models.DateField(verbose_name='Durchgefuehrt am')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Durchgefuehrt von')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='maintenance.maintenanceplan', verbose_name='Wartungsplan')),
            ],
            options={
                'verbose_name': 'Wartungsereignis',
                'verbose_name_plural': 'Wartungsereignisse',
                'ordering': ['-performed_on', '-id'],
            },
        ),
    ]
