# Generated by Django 5.2.12 on 2026-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Asset-ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Kurzname')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorie')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Standort')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Abteilung')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Inbetriebnahme')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('out_of_service', 'Ausser Betrieb')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_id'],
            },
        ),
    ]
